enquetes/urls.py
from django.urls import path

from . import views

app_name = 'enquetes'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('enquete/<int:question_id>/',
         views.QuestionDetail.as_view(), name='question_detail'),
    path('enquente/results/<int:question_id>/',
         views.QuestionResults.as_view(), name='question_results'),
    path('enquete/vote/<int:question_id>/',
         views.VoteView.as_view(), name='vote'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("enquetes.urls")),
    path('admin/', admin.site.urls),
]

enquetes/models.py
from django.db import models


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('de publicação')

    def __str__(self):
        return ("{0} - {1}").format(self.id, self.question_text)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField('Quantidade de votos', default=0)

    def __str__(self):
        return ("{0} - {1}").format(self.question.question_text, self.choice_text)

enquetes/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import View

from .models import Choice, Question

# Create your views here.


class Index(View):
    def get(self, request, *args, **kwargs):
        Questions = Question.objects.all().order_by('-pub_date')[:25]
        context = {'Questions': Questions}
        return render(request, 'enquetes/pages/index.html', context)


class QuestionDetail(View):
    def get(self, request, *args, **kwargs):
        question_id = kwargs['question_id']
        question = get_object_or_404(Question, pk=question_id)
        context = {'question': question}
        return render(request, 'enquetes/pages/question_detail.html', context)


class QuestionResults(View):
    def get(self, request, *args, **kwargs):
        question_id = kwargs['question_id']
        question = get_object_or_404(Question, pk=question_id)
        context = {'question': question}
        return render(request, 'enquetes/pages/question_results.html', context)


class VoteView(View):
    def post(self, request, *args, **kwargs):
        question_id = kwargs['question_id']
        question = get_object_or_404(Question, pk=question_id)
        try:
            selected = question.choice_set.get(pk=request.POST['choice_id'])
        except (KeyError, Question.DoesNotExist):
            contexto = {
                'question': question,
                'msg_erro': 'Selecione uma opção válida!'
            }
            return render(request, 'enquetes/pages/question_detail.html', contexto)
        else:
            selected.votes += 1
            selected.save()
            return HttpResponseRedirect(
                reverse('enquetes:question_results', args=(question.id,))
            )

enquetes/templates/enquetes/pages/index.html
{% extends 'main.html' %} {% block content %}

<body>
  <section
    class="container pt-5 flex flex-col flex justify-between items-center"
  >
    <h2 class="text-5xl">Todas as Enquetes</h2>

    <div class="flex flex-row m-5">
      {% for Question in Questions %}

      <div
        class="rounded-lg background-color-secundary mx-4 w-50 p-4"
      >
        <div class="">
          <h3 class="mb-4">{{ Question.question_text }}</h3>
          <div class="flex flex-col">
            <a
              href="{% url 'enquetes:question_detail' Question.id %}"
              class="rounded background-color-primary p-2 text-white text-center mb-2"
            >
              votar
            </a>
            <a href="{% url 'enquetes:question_results' Question.id %}"
              class="rounded background-black p-2 text-white text-center"
            >
              ver parcial</a
            >
          </div>
        </div>
      </div>

      {% endfor %}
    </div>
  </section>

  {% endblock %}
</body>

enquetes/templates/enquetes/pages/question_detail.html
{% include 'enquetes/partials/head.html' %} 
{% include 'enquetes/partials/navbar.html' %}
<body>
  {% if msg_erro %}
  <hr />
  <b>{{ msg_erro }}</b>
  <hr />
  {% endif %} {{ question.question_text }}
  <br />
  <form action="{% url 'enquetes:vote' question.id %}" method="post">
    {% csrf_token %}
    <ul>
      {% for choice in question.choice_set.all %}

      <input
        type="radio"
        name="choice_id"
        value="{{ choice.id }}"
        id="alt{{ forloop.counter }}"
      />
      <label for="alt{{ forloop.counter }}"> {{ choice.choice_text }} </label
      ><br />

      {% endfor %}
    </ul>

    <input type="submit" value="Registre o seu voto" />
  </form>
</body>

enquetes/templates/enquetes/pages/question_results.html
{% include 'enquetes/partials/head.html' %}
{% include 'enquetes/partials/navbar.html' %}
{{ question.question_text }} 
  <br>
  {% for choice in question.choice_set.all %}
  <label for="alt{{ forloop.counter }}"> {{ choice.choice_text }} - {{ choice.votes }}</label><br />
  {% endfor %}

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link rel="stylesheet" href="{% static 'enquetes/css/main-style.css' %}">
    <title>+ Enquetes</title>
  </head>
  <body>
    {% include 'navbar.html' %} {% block content%} {% endblock %}
  </body>
</html>

templates/navbar.html
{% load static %} {% block content %}

<nav class="background-light-black px-7 py-3 flex justify-between items-center">
  <a href="/"
    ><img
      src="{% static 'enquetes/images/Logo.png' %}"
      alt="+Enquetes Logo"
      class="w-10"
  /></a>
  <form
    action="GET"
    class="background-grey rounded-lg h-8 px-4 flex items-center"
  >
    <input
      type="text"
      placeholder="Pesquise por nome ou tag"
      class="bg-transparent outline-0 text-gray-800"
    />
    <button><i class="fa-solid fa-magnifying-glass text-grey"></i></button>
  </form>

  <div class="flex justify-between items-center">
    <i class="fa-solid fa-circle-user text-4xl"></i>
    <i class="fa-solid fa-angle-down text-2xl text-grey mx-2"></i>
  </div>
</nav>

{% endblock %}